package env

import (
	"os"
	"path/filepath"
	"testing"
)

func TestReadDebugMK(t *testing.T) {
	dir := t.TempDir()
	content := `# Auto-generated by SDK — do not edit
TARGET_NAME              := run_leds
TARGET_SOC               := k1921vg1t
TARGET_LINKER            := flash
TARGET_INTERFACE         := jlink
TARGET_GDB_PORT          := 3333
TARGET_OCD_TARGET_CFG    := /sdk/tools/ocd/target/k1921vg1t.cfg
TARGET_OCD_INTERFACE_CFG := /sdk/tools/ocd/interface/jlink.cfg
TARGET_OCD_EXTRA_ARGS    :=
`
	if err := os.WriteFile(filepath.Join(dir, "debug.mk"), []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	cfg, err := ReadDebugMK(dir)
	if err != nil {
		t.Fatalf("ReadDebugMK: %v", err)
	}

	if cfg.SoC != "k1921vg1t" {
		t.Errorf("SoC = %q, want k1921vg1t", cfg.SoC)
	}
	if cfg.Interface != "jlink" {
		t.Errorf("Interface = %q, want jlink", cfg.Interface)
	}
	if cfg.GDBPort != "3333" {
		t.Errorf("GDBPort = %q, want 3333", cfg.GDBPort)
	}
	if cfg.OCDExtraArgs != "" {
		t.Errorf("OCDExtraArgs = %q, want empty", cfg.OCDExtraArgs)
	}
}

func TestReadDebugMKNotFound(t *testing.T) {
	_, err := ReadDebugMK(t.TempDir())
	if err != ErrDebugMkNotFound {
		t.Fatalf("err = %v, want ErrDebugMkNotFound", err)
	}
}
